version: '3'

services:
  currency-python:  
    build: ./python-docker
    depends_on:
      - db
      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment: 
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "3307:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
  
    